"""add constraints, server defaults, drop redundant indexes

Revision ID: e45f9de948ab
Revises: eddd68e0d62a
Create Date: 2026-08-04 15:14:21.939378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e45f9de948ab'
down_revision: Union[str, Sequence[str], None] = 'eddd68e0d62a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. DATA FIX FIRST — 'failed' is a legacy status (Day 6 wrote it, Day 11
    #    renamed it to 'dead'). The CHECK below fails without this.
    op.execute("UPDATE events SET status = 'dead' WHERE status = 'failed'")

    # 2. autogenerated
    op.add_column('endpoints', sa.Column('created_at', sa.DateTime(timezone=True),
                                         server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_endpoints_id'), table_name='endpoints')
    op.drop_index(op.f('ix_events_id'), table_name='events')

    # 3. server defaults on existing columns (autogenerate skips these)
    op.alter_column('endpoints', 'is_active',
                    existing_type=sa.Boolean(), server_default=sa.text('true'))
    op.alter_column('events', 'status',
                    existing_type=sa.String(), server_default='pending')
    op.alter_column('events', 'created_at',
                    existing_type=sa.DateTime(timezone=True), server_default=sa.text('now()'))
    op.alter_column('delivery_attempts', 'attempted_at',
                    existing_type=sa.DateTime(timezone=True), server_default=sa.text('now()'))

    # 4. CHECK constraints (autogenerate skips these)
    op.create_check_constraint(
        'ck_events_status', 'events',
        "status IN ('pending', 'delivered', 'dead')")
    op.create_check_constraint(
        'ck_delivery_attempts_attempt_number', 'delivery_attempts',
        'attempt_number > 0')


def downgrade() -> None:
    """Downgrade schema.

    NOTE: the 'failed' -> 'dead' backfill in upgrade() is NOT reversible.
    Once merged, those rows are indistinguishable from rows that were always
    'dead'. This downgrade restores the schema, not the original data.
    """
    op.drop_constraint('ck_delivery_attempts_attempt_number', 'delivery_attempts', type_='check')
    op.drop_constraint('ck_events_status', 'events', type_='check')

    op.alter_column('delivery_attempts', 'attempted_at',
                    existing_type=sa.DateTime(timezone=True), server_default=None)
    op.alter_column('events', 'created_at',
                    existing_type=sa.DateTime(timezone=True), server_default=None)
    op.alter_column('events', 'status',
                    existing_type=sa.String(), server_default=None)
    op.alter_column('endpoints', 'is_active',
                    existing_type=sa.Boolean(), server_default=None)

    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_endpoints_id'), 'endpoints', ['id'], unique=False)
    op.drop_column('endpoints', 'created_at')
