"""add attempt_number and duration_ms to delivery_attempt

Revision ID: eddd68e0d62a
Revises: 5c96e9a879d3
Create Date: 2026-07-14 12:01:25.663678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eddd68e0d62a'
down_revision: Union[str, Sequence[str], None] = '5c96e9a879d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('delivery_attempts',
        sa.Column('attempt_number', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('delivery_attempts', 'attempt_number', server_default=None)

    op.add_column('delivery_attempts',
        sa.Column('duration_ms', sa.Integer(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_attempts', 'duration_ms')
    op.drop_column('delivery_attempts', 'attempt_number')
    # ### end Alembic commands ###
